base_model:
  model_name: "resnet18"

  # Null or path to checkpoint
  resume_path: "../Pretrained/MIT-BIH/Base/Full/resnet18_ep3_i128/resnet18_ep3_i128.pth"

  epochs: 2
  image_size: 128
  batch_size: 128

  train_path: "/data/tavonputl/data/MIT-BIH/Datasets/Resolution-128/image_full_train.hdf5"
  test_path: "/data/tavonputl/data/MIT-BIH/Datasets/Resolution-128/image_full_test.hdf5"
  save_dir: "../Pretrained/MIT-BIH/Base/Full"

  preload_train: False
  preload_test: False

  evaluate: True
  save_best: True

distributed:
  do: True
  resume_from_distributed: True
  world_size: 2